<?php

class App_Error
{
	const INVALID_GAME_ID = 100;
	const INVALID_TYPE_IDENTIFIER = 101;
	const ACHIEVEMENT_TYPE_EXISTS = 102;
	const ACHIEVEMENT_LEVEL_MISSING = 103;
	const ACHIEVEMENT_GAME_MISMATCH = 105;
	const ACHIEVEMENT_LEVEL_MISMATCH = 106;
    const ACHIEVEMENT_NOT_FOUND = 110;
    const ACHIEVEMENT_TYPE_NOT_FOUND = 112;
    const GLORY_ALREADY_FETCHED = 150;
    const CANNOT_FETCH_GLORY = 151;
    const INVALID_USER_ID = 161;
    const INVALID_VALUE = 162;
    const INVALID_PARAMS = 170;
    const GENERAL = 999;
}